name: PR Create Actions
on:
   pull_request:
       types: [opened]
       branches: [main, riyash/9.0, riyash/8.0, release/9.0.1]
jobs:
  post-processing-flow:
    name: "PR create processing"
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
         python-version: '3.8.10'
    - name: Install python dependencies
      run: |
        pip install requests
    - name: Commit Title Check
      env:
        TICKET_ID: Dummy_field
      run: |
        echo "Login ${{ github.event.pull_request.user.login }}"
        echo "Repo ${{ github.event.repository.full_name }}"
        echo "PR link ${{ github.event.pull_request.html_url }}"
        echo "Branch ${{ github.event.pull_request.base.ref }}"
        echo "${{ toJSON( github.event) }}"
        export TICKET_ID=$(python .github/scm_scripts/title_check.py '${{ github.event.head_commit.message }}')
        echo "TICKET_ID=$TICKET_ID" >> $GITHUB_ENV
