name: Post Merge Actions
on:
   pull_request:
       types: [opened, closed]
       branches:
           - main
jobs:
  post-processing-flow:
    name: "Sample post processing"
    runs-on: ubuntu-latest
    steps:
    - name: Echo statement
      run: |
        echo "Lets see if it prints"
