# .github/workflows/logger.yaml
name: Code Commit PreProcessing
on: push

jobs:
  log-github-event-goodies:
    name: "Code Commit Compliance Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checking
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
           python-version: '3.8.10'
      - name: Install python dependencies
        run: |
          pip install requests
      - name: Check Commit Title JIRA & VersionOne
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          V1_TOKEN: ${{ secrets.V1_TOKEN }}
        run: |
          python .github/scm_scripts/ib_check.py "${{ github.event.head_commit.message }}" "${{ env.JIRA_TOKEN }}" "${{ env.V1_TOKEN }}"
          export JIRA_ID=$(echo "${{ github.event.head_commit_message }}" | awk -F':' '{print $1}')
          echo "JIRA_ID=$JIRA_ID" >> $GITHUB_ENV
      - name: JIRA Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_USER_EMAIL: rhaneefa@infoblox.com
          JIRA_API_TOKEN: SXytw1cH4d7FDMHaKoQO904E
      - name: JIRA Comment
        uses: atlassian/gajira-comment@master
        with:
          issue: ${{ env.JIRA_ID }}
          comment:  ${{ github.event.pusher.name }} pushed to repository ${{ github.event.repository.full_name }}
        
