# .github/workflows/logger.yaml
name: Code Commit PreProcessing
on:
  push:
    branches-ignore:
      - main

jobs:
  github-preprocessing:
    name: "Code Commit Compliance Check"
    runs-on: ubuntu-latest
    steps:
      - name: Env variables
        run: |
          echo "${{toJSON(github)}}"
      - name: Checking
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
           python-version: '3.8.10'
      - name: Install python dependencies
        run: |
          pip install requests
      - uses: kceb/pull-request-url-action@v1
        id: pr-url
      - name: Get PR Link
        run: echo "${{ steps.pr-url.outputs.url }}"
      - name: Check Commit Title JIRA & VersionOne
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          V1_TOKEN: ${{ secrets.V1_TOKEN }}
        run: |
          python .github/scm_scripts/ib_check.py "${{ github.event.head_commit.message }}" "${{ env.JIRA_TOKEN }}" "${{ env.V1_TOKEN }}"
