# .github/workflows/logger.yaml
name: Commit Message Check
on: push

jobs:
  log-github-event-goodies:
    name: "Check for non-ascii in commit message"
    runs-on: ubuntu-latest
    steps:
      - name: Checking
        shell: bash
        run: |
          if [[ ${{ github.event.head_commit.message }} = *[![:ascii:]]* ]]; then exit 1; else exit 0; fi
