# .github/workflows/logger.yaml
name: Source code compliance check
on: push

jobs:
  log-github-event-goodies:
    name: "Infoblox Source Code Commit Compliance"
    runs-on: ubuntu-latest
    steps:
      - name: Checking
        uses: actions/checkout@v2
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          V1_TOKEN: ${{ secrets.V1_TOKEN }}
      - name: Set up python
        uses: actions/setup-python@v2
        with:
           python-version: '3.8.10'
      - run: |
          pip install requests
          python .github/scm_scripts/ib_check.py "${{ github.event.head_commit.message }}" "${{ env.JIRA_TOKEN }}" "${{ env.V1_TOKEN }}"
